<?php

return array (
  'name' => '金亚包装',
  'beian' => '皖ICP备15022698号',
  'cdnurl' => '',
  'version' => '1.0.1',
  'timezone' => 'Asia/Shanghai',
  'forbiddenip' => '',
  'languages' => 
  array (
    'backend' => 'zh-cn',
    'frontend' => 'zh-cn',
  ),
  'fixedpage' => 'dashboard',
  'categorytype' => 
  array (
    'default' => 'Default',
    'page' => 'Page',
    'article' => 'Article',
    'test' => 'Test',
  ),
  'configgroup' => 
  array (
    'basic' => 'Basic',
    'email' => 'Email',
    'dictionary' => 'Dictionary',
    'user' => 'User',
    'example' => 'Example',
  ),
  'mail_type' => '1',
  'mail_smtp_host' => 'smtp.qq.com',
  'mail_smtp_port' => '465',
  'mail_smtp_user' => '',
  'mail_smtp_pass' => '',
  'mail_verify_type' => '2',
  'mail_from' => '',
  'attachmentcategory' => 
  array (
    'category1' => 'Category1',
    'category2' => 'Category2',
    'custom' => 'Custom',
  ),
  'cms_company' => '安徽科创美涂料科技股份有限公司',
  'cms_slogan' => '科创美是一家专门从事建筑墙面涂料生产与施工的高新技术企业，提供墙面、地面、屋面的综合涂料解决方案',
  'cms_logo' => '/uploads/20260825/dafe2d34dde77abb9247b226ff2c2406.png',
  'cms_pc_news_banner' => '',
  'cms_pc_about_banner' => '',
  'cms_mobile_news_banner' => '',
  'cms_mobile_about_banner' => '',
  'cms_wechat_qr' => '/uploads/cms-clone/pc/resource/images/4e3d65d0ac04484b8426f9a10abf6614_22.jpg',
  'cms_douyin_qr' => '/uploads/cms-clone/pc/resource/images/4e3d65d0ac04484b8426f9a10abf6614_28.jpg',
  'cms_kuaishou_qr' => '/uploads/cms-clone/pc/resource/images/4e3d65d0ac04484b8426f9a10abf6614_24.jpg',
  'cms_xiaohongshu_qr' => '/uploads/cms-clone/pc/resource/images/4e3d65d0ac04484b8426f9a10abf6614_30.jpg',
  'cms_video_qr' => '/uploads/cms-clone/pc/resource/images/4e3d65d0ac04484b8426f9a10abf6614_26.jpg',
  'cms_bilibili_qr' => '/uploads/cms-clone/pc/resource/images/c2825f5e9424452ba59dc8d30160dbe2_2.jpg',
  'cms_phone' => '400-006-8683',
  'cms_email' => '772422624@qq.com',
  'cms_address' => '安徽省合肥市肥西经济开发区万佛山路18号',
  'cms_copyright_year' => '2025',
  'cms_tech_support' => '单仁牛商（股票代码：830770）',
  'cms_service_wecom_url' => '',
  'cms_service_wechat_qr' => '',
  'cms_service_wechat_name' => '金亚包装业务客服',
  'cms_service_wechat_tip' => '扫码添加客服，获取包装解决方案',
  'cms_service_hours' => '8:30-18:00',
  'cms_pc_product_banner' => '',
  'cms_mobile_product_banner' => '',
);
